#!/usr/bin/dash

color_crit="#EC819E"
color_fast="#FFA000"
color_idle="#FFFFFF"
freq_raw=$(cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq)

freq_ghz=$((freq_raw/1000000))

freq_10_mhz=$(((freq_raw-freq_ghz*1000000)/10000))
if [ $freq_ghz -gt 1 ];
then
	color=$color_crit
elif [ $freq_ghz -gt 0 ];	    	
then
	color=$color_fast	
else
	color=$color_idle
fi
if [ $freq_10_mhz -lt 10 ];
then
	echo  "${freq_ghz}.0${freq_10_mhz}GHz"
	echo  "${freq_ghz}.0${freq_10_mhz}GHz"
else
	echo  "${freq_ghz}.${freq_10_mhz}GHz"
	echo  "${freq_ghz}.${freq_10_mhz}GHz"
fi
	echo "$color"
